version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
