[package]
authors = ["Alexander Serowy <serowy@hotmail.com>"]
edition = "2018"
name = "docker2mqtt"
version = "0.0.1"

[dependencies]
enum-iterator = "0.6"
paho-mqtt = "0.9"
rs-docker = "0.0.58"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
