[package]
authors = ["Alexander Serowy <serowy@hotmail.com>"]
edition = "2018"
name = "docker2mqtt"
version = "0.0.1"

[dependencies]
enum-iterator = "0.6"
rs-docker = "0.0.58"
rumqttc = "0.5"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tokio = {version = "1", features = ["full"]}
