[package]
name = "docker2mqtt"
version = "0.1.0"
authors = ["Alexander Serowy <serowy@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
