version: "3.0"
services:
  # dev
  docker2mqtt:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - .:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"

  # home assistant
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./.devcontainer/mosquitto/config:/mosquitto/config
      - ./.devcontainer/mosquitto/data:/mosquitto/data
      - ./.devcontainer/mosquitto/log:/mosquitto/log
  home-assistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    restart: always
    depends_on:
      - mosquitto
    ports:
      - "8123:8123"
    volumes:
      - ./.devcontainer/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
