docker:
  persist_state: true
  # stream_logs: # default: true
  stream_logs_container:
    - silly_brattain
  stream_logs_filter:
    - domain

hassio:
  discovery: true
  # discovery_prefix: # default: homeassistant
  # device_prefix: # default: docker

logging:
  level: DEBUG

mqtt:
  client_id: hostname
  # connection_timeout: # default: 20
  host: mosquitto
  # keep_alive: # default: 30
  # password: # default: None
  port: 1883
  qos: 1 # default: 0
  # username: # default: None
