name: multi arc pipeline for docker hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login
        run: echo ${{ secrets.DOCKER_ATOKEN }} | docker login -u serowy --password-stdin
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: build
        run: |
          docker buildx build --push \
            --tag serowy/docker2mqtt:latest \
            --platform linux/arm64/v8,linux/arm/v6,linux/arm/v7 .
