name: armv7_pipeline

on:
  push:
    branches-ignore:
      - "!main"
    tags:
      - "v*.*.*"

jobs:
  linux_armv7:
    name: linux_armv7
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set_version_tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/release/}" >> $GITHUB_ENV

      - name: setup_toolchain_armv7
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-musleabihf
          override: true

      - name: cargo_dependency_cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo_build_armv7
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-musleabihf --release

      - name: docker_login
        run: echo ${{ secrets.DOCKER_ATOKEN }} | docker login -u serowy --password-stdin

      - name: docker_setup_qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: docker_setup_buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: docker_build
        run: |
          docker buildx build --push \
            --tag serowy/docker2mqtt:$RELEASE_VERSION \
            --tag serowy/docker2mqtt:latest \
            --platform linux/arm/v7 .
